caracteristicas = {"fue": 0, "agi": 0, "con": 0, "int": 0, "i": 0, "pre": 0}
bonificador_car = {"fue": 0, "agi": 0, "con": 0, "int": 0,"i": 0, "pre": 0}
habilidades = {"mym":{"sa": 0, "c": 0, "ce": 0, "cm": 0, "co": 0},
                "arma":{"filo": 0, "contundentes": 0, "dos_manos": 0, "arrojadizas": 0,"proyectiles": 0, "asta": 0},
                "generales":{"trepar": 0, "montar": 0, "nadar": 0, "rastrear": 0,},
                "subterfugio":{"emboscar": 0, "asechar_esconderse": 0, "abrir_cerraduras": 0, "desactivar_trampas": 0},
                "magicas":{"leer_runas": 0, "usar_objeto": 0, "sortilegio_dirigido": 0, "sortilegio_base": 0},
                "fisico":{"vida":0, "persepcion": 0},
                "sortilegio":[],
                "idiomas":{},
                "historial": 0,}
resistencias = {"esencia": 0, "canalizacion": 0, "venenos": 0, "enfermedades": 0, "frio": 0, "calor": 0}
secundarias = {}
billetera = {"mm":0, "mo":0, "mp":0, "mb":0, "mc":0, "me":0}
experiencia = {"lvl": 0, "xp": 0, "movimiento": 1}
inventario = {"armas":{}, "objetos magicos":{}, "accesorios":{}, "hierbas y pociones":{}, "armadura":{}}

numero_por_car = {1:-35, 3:-30, 5:-25, 7:-20, 9:-15, 14:-10, 19:-5, 74:0, 89:5, 94:10, 97:15, 99:20, 100:25, 101:30, 102:35}

raza = {3:"hobbit", 8:"umli", 21:"enano", 25:"wose", 75:{5:"dunedain",10:"rohirrim", 15:"beornida", 20:"bosques", 25:"dorwinrim", 30:"lossoth"
    , 54:"campesino", 78:"burgues", 83:"dunlendino", 86:"este", 89:"haradrim", 92:"corsario", 95:"variag", 100:"numeroniano"},
    78:"medio elfo", 91:"silvano", 97:"sindar", 100:"noldor"}
bonificador_raza = {
    "hobbit": {"bonificador":[-20, 15, 15, 0,-5,-5],
               "adolescencia":{"sa":1,"c":0,"ce":0,"cm":0,"co":0,
                                "filo":0,"contundente":0,"dos_manos":0,"arrojadizas":2,"proyectiles":2,"asta":0,
                                "trepar":2,"montar":0,"nadar":0,"rastrear":0,
                                "emboscar":0,"asechar_esconderse":5,"abrir_cerraduras":1,"desactivar_trampas":1,
                                "leer_runas":0,"usar_objeto":0,"sortilegio_base":0,"sortilegio_dirigido":0,
                                "vida":2,"persepcion":4,"sortilegio":0,"idiomas":3,"historial":5},
               "resistencias":[50,20,30,15,0,0]},
    "umli": {"characteristicas":[5,0,10,0,-5,-5],"adolescencia":{"sa":1,"c":3,"ce":3,"cm":0,"co":0,
                                "filo":0,"contundente":3,"dos_manos":1,"arrojadizas":1,"proyectiles":0,"asta":0,
                                "trepar":0,"montar":0,"nadar":1,"rastrear":0,
                                "emboscar":0,"asechar_esconderse":1,"abrir_cerraduras":0,"desactivar_trampas":0,
                                "leer_runas":0,"usar_objeto":0,"sortilegio_base":0,"sortilegio_dirigido":0,
                                "vida":2,"persepcion":1,"sortilegio":5,"idiomas":3,"historial":4},
             "resistencias":[20,0,5,5,0,0]},
    "enano": {"characteristicas":[5,-5,15,0,-5,-5],
              "adolescencia":{"sa":1,"c":0,"ce":1,"cm":3,"co":0,
                                "filo":0,"contundente":4,"dos_manos":0,"arrojadizas":1,"proyectiles":0,"asta":0,
                                "trepar":1,"montar":0,"nadar":0,"rastrear":0,
                                "emboscar":0,"asechar_esconderse":0,"abrir_cerraduras":1,"desactivar_trampas":1,
                                "leer_runas":0,"usar_objeto":0,"sortilegio_base":0,"sortilegio_dirigido":0,
                                "vida":3,"persepcion":1,"sortilegio":3,"idiomas":4,"historial":4},
              "resistencias":[40,0,10,10,0,0]},
    "wose": {"characteristicas":[0,0,5,0,0,-5],"adolescencia":[1,3,0,0,0,2,0,0,4,0,1,3,0,2,0,2,4,0,0,0,0,0,0,3,1,5,2,5],
             "resistencias":[20,0,0,0,0,0]},
    "humano": {"characteristicas":[5,0,0,0,0,0],
               "adolescencia":{
                    "beornida": {"sa":1,"c":0,"ce":0,"cm":0,"co":0,
                                "filo":0,"contundente":0,"dos_manos":1,"arrojadizas":1,"proyectiles":0,"asta":2,
                                "trepar":2,"montar":0,"nadar":2,"rastrear":0,
                                "emboscar":0,"asechar_esconderse":4,"abrir_cerraduras":0,"desactivar_trampas":0,
                                "leer_runas":0,"usar_objeto":0,"sortilegio_base":0,"sortilegio_dirigido":0,
                                "vida":3,"persepcion":1,"sortilegio":3,"idiomas":3,"historial":5},
                    
                    "numeroniano": {"sa":1,"c":0,"ce":0,"cm":2,"co":0,
                                "filo":1,"contundente":0,"dos_manos":0,"arrojadizas":1,"proyectiles":1,"asta":0,
                                "trepar":0,"montar":1,"nadar":3,"rastrear":1,
                                "emboscar":0,"asechar_esconderse":0,"abrir_cerraduras":0,"desactivar_trampas":0,
                                "leer_runas":1,"usar_objeto":1,"sortilegio_base":0,"sortilegio_dirigido":0,
                                "vida":2,"persepcion":0,"sortilegio":10,"idiomas":6,"historial":3},
                    
                    "corsario": {"sa":1,"c":0,"ce":2,"cm":0,"co":0,
                                "filo":2,"contundente":0,"dos_manos":0,"arrojadizas":1,"proyectiles":1,"asta":0,
                                "trepar":0,"montar":0,"nadar":5,"rastrear":0,
                                "emboscar":0,"asechar_esconderse":0,"abrir_cerraduras":0,"desactivar_trampas":0,
                                "leer_runas":0,"usar_objeto":0,"sortilegio_base":0,"sortilegio_dirigido":0,
                                "vida":2,"persepcion":0,"sortilegio":5,"idiomas":5,"historial":5},
                    
                    "dorwinrim": {"sa":1,"c":0,"ce":1,"cm":0,"co":0,
                                "filo":0,"contundente":1,"dos_manos":0,"arrojadizas":1,"proyectiles":1,"asta":1,
                                "trepar":0,"montar":2,"nadar":1,"rastrear":0,
                                "emboscar":0,"asechar_esconderse":0,"abrir_cerraduras":0,"desactivar_trampas":0,
                                "leer_runas":0,"usar_objeto":0,"sortilegio_base":0,"sortilegio_dirigido":0,
                                "vida":1,"persepcion":0,"sortilegio":10,"idiomas":5,"historial":5},
                    
                    "dunlendinos": {"sa":1,"c":0,"ce":1,"cm":0,"co":0,
                                "filo":0,"contundente":1,"dos_manos":0,"arrojadizas":2,"proyectiles":1,"asta":2,
                                "trepar":5,"montar":0,"nadar":1,"rastrear":0,
                                "emboscar":0,"asechar_esconderse":2,"abrir_cerraduras":0,"desactivar_trampas":0,
                                "leer_runas":0,"usar_objeto":0,"sortilegio_base":0,"sortilegio_dirigido":0,
                                "vida":3,"persepcion":1,"sortilegio":2,"idiomas":2,"historial":4},
                    
                    "este": {"sa":1,"c":0,"ce":0,"cm":0,"co":0,
                                "filo":1,"contundente":0,"dos_manos":0,"arrojadizas":1,"proyectiles":2,"asta":2,
                                "trepar":0,"montar":5,"nadar":0,"rastrear":0,
                                "emboscar":0,"asechar_esconderse":0,"abrir_cerraduras":0,"desactivar_trampas":0,
                                "leer_runas":0,"usar_objeto":0,"sortilegio_base":0,"sortilegio_dirigido":0,
                                "vida":2,"persepcion":1,"sortilegio":2,"idiomas":2,"historial":4},
                    
                    "haradrim": {"sa":1,"c":1,"ce":0,"cm":0,"co":0,
                                "filo":1,"contundente":0,"dos_manos":0,"arrojadizas":1,"proyectiles":0,"asta":2,
                                "trepar":0,"montar":7,"nadar":0,"rastrear":0,
                                "emboscar":0,"asechar_esconderse":0,"abrir_cerraduras":0,"desactivar_trampas":0,
                                "leer_runas":0,"usar_objeto":0,"sortilegio_base":0,"sortilegio_dirigido":0,
                                "vida":2,"persepcion":1,"sortilegio":2,"idiomas":3,"historial":5},
                    
                    "lossoth": {"sa":1,"c":3,"ce":0,"cm":0,"co":0,
                                "filo":0,"contundente":0,"dos_manos":0,"arrojadizas":3,"proyectiles":0,"asta":2,
                                "trepar":0,"montar":0,"nadar":2,"rastrear":0,
                                "emboscar":0,"asechar_esconderse":4,"abrir_cerraduras":0,"desactivar_trampas":0,
                                "leer_runas":0,"usar_objeto":0,"sortilegio_base":0,"sortilegio_dirigido":0,
                                "vida":3,"persepcion":1,"sortilegio":5,"idiomas":1,"historial":4},

                    "rohirrim": {"sa":1,"c":0,"ce":1,"cm":2,"co":0,
                                "filo":2,"contundente":0,"dos_manos":0,"arrojadizas":0,"proyectiles":1,"asta":1,
                                "trepar":0,"montar":8,"nadar":1,"rastrear":0,
                                "emboscar":0,"asechar_esconderse":0,"abrir_cerraduras":0,"desactivar_trampas":0,
                                "leer_runas":0,"usar_objeto":0,"sortilegio_base":0,"sortilegio_dirigido":0,
                                "vida":3,"persepcion":1,"sortilegio":3,"idiomas":4,"historial":5},
                    
                    "campesinos": {"sa":1,"c":1,"ce":1,"cm":1,"co":0,
                                "filo":1,"contundente":0,"dos_manos":0,"arrojadizas":1,"proyectiles":1,"asta":1,
                                "trepar":0,"montar":1,"nadar":1,"rastrear":0,
                                "emboscar":0,"asechar_esconderse":1,"abrir_cerraduras":0,"desactivar_trampas":0,
                                "leer_runas":0,"usar_objeto":0,"sortilegio_base":0,"sortilegio_dirigido":0,
                                "vida":2,"persepcion":1,"sortilegio":3,"idiomas":4,"historial":5},

                    "burgueses": {"sa":1,"c":0,"ce":0,"cm":0,"co":0,
                                "filo":1,"contundente":0,"dos_manos":0,"arrojadizas":0,"proyectiles":1,"asta":0,
                                "trepar":0,"montar":0,"nadar":1,"rastrear":0,
                                "emboscar":0,"asechar_esconderse":0,"abrir_cerraduras":0,"desactivar_trampas":0,
                                "leer_runas":1,"usar_objeto":1,"sortilegio_base":0,"sortilegio_dirigido":0,
                                "vida":1,"persepcion":1,"sortilegio":15,"idiomas":5,"historial":5},
                    
                    "variag": {"sa":1,"c":1,"ce":0,"cm":0,"co":0,
                                "filo":2,"contundente":0,"dos_manos":0,"arrojadizas":1,"proyectiles":1,"asta":1,
                                "trepar":0,"montar":4,"nadar":0,"rastrear":0,
                                "emboscar":0,"asechar_esconderse":1,"abrir_cerraduras":0,"desactivar_trampas":0,
                                "leer_runas":0,"usar_objeto":0,"sortilegio_base":0,"sortilegio_dirigido":0,
                                "vida":2,"persepcion":1,"sortilegio":5,"idiomas":3,"historial":4},
                    
                    "bosques": {"sa":1,"c":1,"ce":0,"cm":0,"co":0,
                                "filo":1,"contundente":0,"dos_manos":0,"arrojadizas":1,"proyectiles":1,"asta":1,
                                "trepar":3,"montar":0,"nadar":1,"rastrear":0,
                                "emboscar":0,"asechar_esconderse":4,"abrir_cerraduras":0,"desactivar_trampas":0,
                                "leer_runas":0,"usar_objeto":0,"sortilegio_base":0,"sortilegio_dirigido":0,
                                "vida":2,"persepcion":1,"sortilegio":3,"idiomas":2,"historial":5},
                            },
               "resistencias":[0,0,0,0,0,0]},
    "dunedain": {"characteristicas":[5,0,10,0,0,5],
                 "adolescencia":{"sa":1,"c":0,"ce":1,"cm":2,"co":0,
                                "filo":2,"contundente":0,"dos_manos":1,"arrojadizas":0,"proyectiles":1,"asta":1,
                                "trepar":0,"montar":1,"nadar":1,"rastrear":0,
                                "emboscar":0,"asechar_esconderse":0,"abrir_cerraduras":0,"desactivar_trampas":0,
                                "leer_runas":1,"usar_objeto":1,"sortilegio_base":0,"sortilegio_dirigido":0,
                                "vida":3,"persepcion":0,"sortilegio":10,"idiomas":6,"historial":3},
                 "resistencias":[0,0,5,5,0,0]},
    "medio elfo": {"characteristicas":[5,5,5,0,0,5],
                   "adolescencia":{"sa":1,"c":0,"ce":1,"cm":1,"co":0,
                                "filo":1,"contundente":0,"dos_manos":0,"arrojadizas":0,"proyectiles":2,"asta":0,
                                "trepar":1,"montar":1,"nadar":1,"rastrear":0,
                                "emboscar":0,"asechar_esconderse":2,"abrir_cerraduras":0,"desactivar_trampas":0,
                                "leer_runas":1,"usar_objeto":0,"sortilegio_base":0,"sortilegio_dirigido":0,
                                "vida":1,"persepcion":1,"sortilegio":10,"idiomas":4,"historial":3},
                   "resistencias":[0,0,5,50,0,0]},
    "silvano": {"characteristicas":[0,10,0,0,5,5],
                "adolescencia":{"sa":1,"c":0,"ce":0,"cm":0,"co":0,
                                "filo":1,"contundente":0,"dos_manos":0,"arrojadizas":0,"proyectiles":3,"asta":0,
                                "trepar":2,"montar":1,"nadar":3,"rastrear":0,
                                "emboscar":0,"asechar_esconderse":4,"abrir_cerraduras":0,"desactivar_trampas":0,
                                "leer_runas":1,"usar_objeto":0,"sortilegio_base":0,"sortilegio_dirigido":0,
                                "vida":1,"persepcion":3,"sortilegio":20,"idiomas":6,"historial":4},
                "resistencias":[0,0,10,100,0,0]},
    "sindar": {"characteristicas":[0,10,5,0,5,10],
               "adolescencia":{"sa":1,"c":0,"ce":0,"cm":0,"co":0,
                                "filo":1,"contundente":0,"dos_manos":0,"arrojadizas":0,"proyectiles":2,"asta":0,
                                "trepar":1,"montar":1,"nadar":2,"rastrear":0,
                                "emboscar":0,"asechar_esconderse":3,"abrir_cerraduras":0,"desactivar_trampas":0,
                                "leer_runas":1,"usar_objeto":1,"sortilegio_base":0,"sortilegio_dirigido":0,
                                "vida":1,"persepcion":3,"sortilegio":30,"idiomas":8,"historial":3},
               "resistencias":[0,0,10,100,0,0]},
    "noldor": {"characteristicas":[0,15,10,5,5,15], 
               "adolescencia":{"sa":1,"c":0,"ce":0,"cm":0,"co":0,
                                "filo":1,"contundente":0,"dos_manos":0,"arrojadizas":0,"proyectiles":1,"asta":0,
                                "trepar":0,"montar":1,"nadar":2,"rastrear":0,
                                "emboscar":0,"asechar_esconderse":2,"abrir_cerraduras":0,"desactivar_trampas":0,
                                "leer_runas":2,"usar_objeto":1,"sortilegio_base":0,"sortilegio_dirigido":0,
                                "vida":1,"persepcion":3,"sortilegio":40,"idiomas":10,"historial":2},
               "resistencias":[0,0,10,100,0,0]},
    "medio orco": {"characteristicas":[5,0,5,0,0,-5],
                   "adolescencia":{"sa":1,"c":1,"ce":3,"cm":1,"co":0,
                                "filo":0,"contundente":3,"dos_manos":0,"arrojadizas":1,"proyectiles":1,"asta":0,
                                "trepar":1,"montar":0,"nadar":0,"rastrear":0,
                                "emboscar":1,"asechar_esconderse":0,"abrir_cerraduras":0,"desactivar_trampas":0,
                                "leer_runas":0,"usar_objeto":0,"sortilegio_base":0,"sortilegio_dirigido":0,
                                "vida":2,"persepcion":0,"sortilegio":0,"idiomas":2,"historial":3},
                   "resistencias":[0,0,10,0,0,0]},
    "orco": {"characteristicas":[5,-5,15,-10,-10,-10],
             "adolescencia":{"sa":1,"c":1,"ce":3,"cm":2,"co":0,
                                "filo":0,"contundente":3,"dos_manos":0,"arrojadizas":1,"proyectiles":0,"asta":1,
                                "trepar":1,"montar":0,"nadar":0,"rastrear":0,
                                "emboscar":1,"asechar_esconderse":0,"abrir_cerraduras":0,"desactivar_trampas":0,
                                "leer_runas":0,"usar_objeto":0,"sortilegio_base":0,"sortilegio_dirigido":0,
                                "vida":2,"persepcion":0,"sortilegio":0,"idiomas":2,"historial":2},
             "resistencias":[0,0,20,5,0,0]},
    "uruk-hai": {"characteristicas":[10,0,20,0,-5,-10],
                 "adolescencia":{"sa":1,"c":1,"ce":3,"cm":3,"co":0,
                                "filo":4,"contundente":1,"dos_manos":1,"arrojadizas":1,"proyectiles":1,"asta":1,
                                "trepar":1,"montar":1,"nadar":0,"rastrear":0,
                                "emboscar":1,"asechar_esconderse":0,"abrir_cerraduras":0,"desactivar_trampas":0,
                                "leer_runas":0,"usar_objeto":0,"sortilegio_base":0,"sortilegio_dirigido":0,
                                "vida":3,"persepcion":1,"sortilegio":0,"idiomas":2,"historial":2},
                 "resistencias":[0,0,20,5,0,0]},
    "medio troll": {"characteristicas":[10,-5,10,-5,-5,-5],
                    "adolescencia":{"sa":1,"c":1,"ce":2,"cm":3,"co":0,
                                "filo":0,"contundente":0,"dos_manos":4,"arrojadizas":2,"proyectiles":0,"asta":0,
                                "trepar":1,"montar":0,"nadar":0,"rastrear":0,
                                "emboscar":1,"asechar_esconderse":0,"abrir_cerraduras":0,"desactivar_trampas":0,
                                "leer_runas":0,"usar_objeto":0,"sortilegio_base":0,"sortilegio_dirigido":0,
                                "vida":4,"persepcion":0,"sortilegio":0,"idiomas":2,"historial":2},
                    "resistencias":[0,0,15,5,0,0]},
    "troll": {"characteristicas":[15,-10,15,-15,-15,-10],
              "adolescencia":{"sa":1,"c":0,"ce":0,"cm":0,"co":0,
                                "filo":0,"contundente":0,"dos_manos":3,"arrojadizas":1,"proyectiles":0,"asta":0,
                                "trepar":1,"montar":0,"nadar":0,"rastrear":0,
                                "emboscar":0,"asechar_esconderse":0,"abrir_cerraduras":0,"desactivar_trampas":0,
                                "leer_runas":0,"usar_objeto":0,"sortilegio_base":0,"sortilegio_dirigido":0,
                                "vida":5,"persepcion":0,"sortilegio":0,"idiomas":2,"historial":1},
              "resistencias":[0,0,30,10,0,0]},
    "olog-hai": {"characteristicas":[20,-5,15,-5,-10,-10],
                 "adolescencia":{"sa":1,"c":0,"ce":0,"cm":0,"co":0,
                                "filo":0,"contundente":0,"dos_manos":5,"arrojadizas":2,"proyectiles":0,"asta":0,
                                "trepar":1,"montar":0,"nadar":0,"rastrear":0,
                                "emboscar":0,"asechar_esconderse":0,"abrir_cerraduras":0,"desactivar_trampas":0,
                                "leer_runas":0,"usar_objeto":0,"sortilegio_base":0,"sortilegio_dirigido":0,
                                "vida":5,"persepcion":1,"sortilegio":0,"idiomas":2,"historial":1},
                 "resistencias":[0,0,20,10,0,0]}
}
player_info = {"id": None, "nombre": None,"familia": None, "raza": None, "estatura": None,
                "peso": None, "genero": None, "edad": None, "pelo": None,
                "ojos": None, "especial Fisico": None, "personalidad": None, "motivacion": None,
                "alineamiento": None, "status": None, "profesion": None, "apariencia": None}
idiomas = []
sortilegios= {}

bonificador_nivel = {
    "explorador":{"arma":1,"generales":1, "subterfugio":2, "fisico":{"persepcion":3}},
    "montaraz": {"arma":2,"generales":3, "fisico":{"persepcion":2}, "subterfugio":{"asechar_esconderse":2}},
    "guerrero": {"arma":3, "generales":1, "fisico":{"vida":2}},
    "bardo": {"arma":1, "generales":1, "subterfugio":1, "magicas":1, "fisico":{"persepcion":1}},
    "mago": {"magico":{"leer_runas":2, "usar_objeto":2, "sortilegio_dirigido":3, "sortilegio_base":2}},
    "animista": {"magico":{"leer_runas":1, "usar_objeto":1,"sortilegio_dirigido":2, "sortilegio_base":2}, "generales":1, "fisico":{"perspcion":1}}
    }

puntos_nivel = {
    "explorador":{"mym":1, "arma":3, "generales":3, "subterfugio":5, "magicas":0, "fisico":2 , "idiomas":1, "sortilegio":0},
    "montaraz":{"mym":2, "arma":3, "generales":4, "subterfugio":2, "magicas":0, "fisico":2 , "idiomas":1, "sortilegio":1},
    "guerrero":{"mym":3, "arma":5, "generales":2, "subterfugio":2, "magicas":0, "fisico":3 , "idiomas":0, "sortilegio":0},
    "bardo":{"mym":0, "arma":2, "generales":2, "subterfugio":2, "magicas":3, "fisico":1 , "idiomas":3, "sortilegio":2},
    "mago":{"mym":0, "arma":0, "generales":2, "subterfugio":0, "magicas":5, "fisico":1 , "idiomas":2, "sortilegio":5},
    "animista":{"mym":1, "arma":1, "generales":2, "subterfugio":1, "magicas":2, "fisico":1 , "idiomas":2, "sortilegio":5},
}
